ALTER TABLE "activities" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "activities" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "activities" ALTER COLUMN "location" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "activity_slots" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "activity_slots" ALTER COLUMN "location" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "booths" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "booths" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "booths" ALTER COLUMN "location" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "booths" ALTER COLUMN "contact_info" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "booths" ALTER COLUMN "booth_type" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "id_name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "location" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "capacity" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "contact_info" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "files" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "files" ALTER COLUMN "file_name_extension" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "files" ALTER COLUMN "size" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "files" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "organizers" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "organizers" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "organizers" ALTER COLUMN "website" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "organizers" ALTER COLUMN "email" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "organizers" ALTER COLUMN "phone_number" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "organizers" ALTER COLUMN "address" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "request_logs" ALTER COLUMN "request_from" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "request_logs" ALTER COLUMN "request_to" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "request_logs" ALTER COLUMN "request_protocol" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "request_logs" ALTER COLUMN "request_method" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_credentials" ALTER COLUMN "password_hash" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "firstname" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "lastname" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "display_name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "contact_email" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "phone_number" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "identity_email" SET DATA TYPE text;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_id_name_not_null" ON "events" USING btree ("id_name") WHERE id_name IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "identity_email_unique_index" ON "users" USING btree (lower("identity_email"));